### PR TITLE
Consistent english strings

### PR DESCRIPTION
**Pull request by gutyina70**
While making a full hungarian translation, I noticed a lot of inconsistencies in the english strings.

Some minor inconsistencies:
- using 3 dots instead of the ellipsis character
- some technical terms (like manifest properties and values) are surrounded by backtics, some aren't
- unnecessary spaces (probably only affects people on weblate and isn't visible in the app)

Inconsistencies I'm not sure about:
- some option titles have every word capitalized (eg. `Soft Keyboard Only If No Hardware`), some don't (eg. `Display background image`)
- possibly unnecessary option descriptions: eg. `Soft keyboard will be disabled.` (why in future tense? imo `Soft keyboard is disabled` or `Soft keyboard disabled` sounds much better), it could be simplified to just `Disabled` and since that's obvious from the state of the option switch, the whole description could be deleted

Please let me know if I'm just too nitpicky and these changes are useless or if it would benefit the project and I should work on it :)

### CODE REVIEW

**Comment by HardcodedCat** [comment]
Being honest, i'd merge it
All help is appreciated

**Comment by HardcodedCat** [comment]
also sorry for those force pushes, i'm trying to fix background images

**Comment by gutyina70** [comment]
Sorry, life is busy for me for about a month, so I can't work on this PR right now.
I'll resolve the conflicts and you can merge it.
When I'll have time I can open a new PR with all the changes I mentioned.

**Comment by HardcodedCat** [comment]
Sure! I was just waiting for your answer before merging

**Comment by HardcodedCat** [comment]
Merged! The commit just glitched (stuck forever in "Rebasing..." so i had to grab from your repo.)

**Pull request closed without merging**
